version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docs` directory
    directory: "/docs"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
