version: '3.8'

services:
  app:
    build: .
    image: drawio-plugin-attackgraphs:1.3.0
    container_name: drawio
    ports:
      - '127.0.0.1:8000:8080'
    volumes:
      - type: bind
        source: ../dist/attackgraphs.js
        target: /usr/local/tomcat/webapps/draw/plugins/attackgraphs.js
      - type: bind
        source: ../dist/attackgraphs.js.map
        target: /usr/local/tomcat/webapps/draw/plugins/attackgraphs.js.map
      - type: bind
        source: ../dist/templates/AttackGraphTemplate_RKL.drawio
        target: /usr/local/tomcat/webapps/draw/templates/basic/attackgraph_RKL.xml
      - type: bind
        source: ../dist/templates/AttackGraphTemplate_TS50701.drawio
        target: /usr/local/tomcat/webapps/draw/templates/basic/attackgraph_TS50701.xml
