name: GitHub Pages

on:
  push:
    paths:
      - '.github/workflows/github-pages.yml'
      - 'docker/**'
      - 'docs/**'
      - 'src/**'
      - 'templates/**'
      - 'package-lock.json'
      - 'package.json'
      - '**.ts'
      - '**.js'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: production
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use Node.js 22.x
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22.x
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - name: Create customized version of draw.io
      run: |
       npm run docker
       npm run start
       docker cp drawio:/usr/local/tomcat/webapps/draw docs/app
       npm run stop

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
      with:
        branch: gh-pages
        folder: docs
