name: GitHub Pages

on:
  push:
    paths:
      - '.github/worklfows/github-pages.yml'
      - 'docker/**'
      - 'docs/**'
      - 'src/**'
      - 'package-lock.json'
      - 'package.json'
      - '**.ts'
      - '**.js'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Create customized version of draw.io
      run: |
       npm run docker
       npm run start
       docker cp drawio:/usr/local/tomcat/webapps/draw docs/app
       npm run stop
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs
